MAIN_URL = 'https://stellarburgers.nomoreparties.site'

ENDPOINT_USER_CREATE = '/api/auth/register'
ENDPOINT_USER_LOGIN = '/api/auth/login'
ENDPOINT_USER_UPDATE_DELETE = '/api/auth/user'
ENDPOINT_ORDER_CREATE_GET = '/api/orders'

POST_REG_USER_ROUTE = f'{MAIN_URL}{ENDPOINT_USER_CREATE}'
POST_LOGIN_USER_ROUTE = f'{MAIN_URL}{ENDPOINT_USER_LOGIN}'
UPDATE_DELETE_USER_ROUTE = f'{MAIN_URL}{ENDPOINT_USER_UPDATE_DELETE}'
POST_GET_ORDER_ROUTE = f'{MAIN_URL}{ENDPOINT_ORDER_CREATE_GET}'
